/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Api;
// uncomment below to import models
//using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ConnectionsEdFiApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ConnectionsEdFiApiTests : IDisposable
    {
        private ConnectionsEdFiApi instance;

        public ConnectionsEdFiApiTests()
        {
            instance = new ConnectionsEdFiApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConnectionsEdFiApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ConnectionsEdFiApi
            //Assert.IsType<ConnectionsEdFiApi>(instance);
        }

        /// <summary>
        /// Test GetTenantDataSyncConnectionEdFiDistricts
        /// </summary>
        [Fact]
        public void GetTenantDataSyncConnectionEdFiDistrictsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string connectionId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncConnectionEdFiDistricts(tenantId, connectionId, apiVersion, xVersion);
            //Assert.IsType<List<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesConnectionEdFiResponse>>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncConnectionEdFiEducationOrganizationIdDescriptors
        /// </summary>
        [Fact]
        public void GetTenantDataSyncConnectionEdFiEducationOrganizationIdDescriptorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string connectionId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncConnectionEdFiEducationOrganizationIdDescriptors(tenantId, connectionId, apiVersion, xVersion);
            //Assert.IsType<List<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesConnectionEdFiResponse>>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncConnectionEdFiSchoolYears
        /// </summary>
        [Fact]
        public void GetTenantDataSyncConnectionEdFiSchoolYearsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string connectionId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncConnectionEdFiSchoolYears(tenantId, connectionId, apiVersion, xVersion);
            //Assert.IsType<List<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesConnectionEdFiResponse>>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncConnectionEdFiStaffIdDescriptors
        /// </summary>
        [Fact]
        public void GetTenantDataSyncConnectionEdFiStaffIdDescriptorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string connectionId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncConnectionEdFiStaffIdDescriptors(tenantId, connectionId, apiVersion, xVersion);
            //Assert.IsType<List<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesConnectionEdFiResponse>>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncConnectionEdFiStudentIdDescriptors
        /// </summary>
        [Fact]
        public void GetTenantDataSyncConnectionEdFiStudentIdDescriptorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string connectionId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncConnectionEdFiStudentIdDescriptors(tenantId, connectionId, apiVersion, xVersion);
            //Assert.IsType<List<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesConnectionEdFiResponse>>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncConnectionEdFiTermDescriptors
        /// </summary>
        [Fact]
        public void GetTenantDataSyncConnectionEdFiTermDescriptorsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string connectionId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncConnectionEdFiTermDescriptors(tenantId, connectionId, apiVersion, xVersion);
            //Assert.IsType<List<EdGraphPlatformHttpAggregatorsTenantApiControllersV1ViewModelsResponsesConnectionEdFiResponse>>(response);
        }
    }
}
