/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Api;
// uncomment below to import models
//using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Test.Api
{
    /// <summary>
    ///  Class for testing JobExecutionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class JobExecutionsApiTests : IDisposable
    {
        private JobExecutionsApi instance;

        public JobExecutionsApiTests()
        {
            instance = new JobExecutionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobExecutionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' JobExecutionsApi
            //Assert.IsType<JobExecutionsApi>(instance);
        }

        /// <summary>
        /// Test GetAllTenantDataSyncJobExecutions
        /// </summary>
        [Fact]
        public void GetAllTenantDataSyncJobExecutionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //int? pageSize = null;
            //int? pageIndex = null;
            //string? orderBy = null;
            //string? filter = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetAllTenantDataSyncJobExecutions(tenantId, jobId, pageSize, pageIndex, orderBy, filter, apiVersion, xVersion);
            //Assert.IsType<DataSyncApiJobExecutionV1JobExecutionListResponsePaginatedItemsViewModel>(response);
        }
    }
}
