/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Api;
// uncomment below to import models
//using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Test.Api
{
    /// <summary>
    ///  Class for testing JobExecutionLogsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class JobExecutionLogsApiTests : IDisposable
    {
        private JobExecutionLogsApi instance;

        public JobExecutionLogsApiTests()
        {
            instance = new JobExecutionLogsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobExecutionLogsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' JobExecutionLogsApi
            //Assert.IsType<JobExecutionLogsApi>(instance);
        }

        /// <summary>
        /// Test GetAllTenantDataSyncJobExecutionLogs
        /// </summary>
        [Fact]
        public void GetAllTenantDataSyncJobExecutionLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string jobExecutionId = null;
            //int? pageSize = null;
            //int? pageIndex = null;
            //string? orderBy = null;
            //string? filter = null;
            //string? search = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetAllTenantDataSyncJobExecutionLogs(tenantId, jobId, jobExecutionId, pageSize, pageIndex, orderBy, filter, search, apiVersion, xVersion);
            //Assert.IsType<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel>(response);
        }
    }
}
