/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Api;
// uncomment below to import models
//using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Test.Api
{
    /// <summary>
    ///  Class for testing JobsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class JobsApiTests : IDisposable
    {
        private JobsApi instance;

        public JobsApiTests()
        {
            instance = new JobsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' JobsApi
            //Assert.IsType<JobsApi>(instance);
        }

        /// <summary>
        /// Test ActivateTenantDataSyncJob
        /// </summary>
        [Fact]
        public void ActivateTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1ActivateJobRequest? dataSyncApiJobV1ActivateJobRequest = null;
            //instance.ActivateTenantDataSyncJob(tenantId, jobId, apiVersion, xVersion, dataSyncApiJobV1ActivateJobRequest);
        }

        /// <summary>
        /// Test CancelTenantDataSyncJob
        /// </summary>
        [Fact]
        public void CancelTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1CancelJobRequest? dataSyncApiJobV1CancelJobRequest = null;
            //instance.CancelTenantDataSyncJob(tenantId, jobId, apiVersion, xVersion, dataSyncApiJobV1CancelJobRequest);
        }

        /// <summary>
        /// Test CreateTenantDataSyncJob
        /// </summary>
        [Fact]
        public void CreateTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1CreateJobRequest? dataSyncApiJobV1CreateJobRequest = null;
            //instance.CreateTenantDataSyncJob(tenantId, apiVersion, xVersion, dataSyncApiJobV1CreateJobRequest);
        }

        /// <summary>
        /// Test DeactivateTenantDataSyncJob
        /// </summary>
        [Fact]
        public void DeactivateTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1DeactivateJobRequest? dataSyncApiJobV1DeactivateJobRequest = null;
            //instance.DeactivateTenantDataSyncJob(tenantId, jobId, apiVersion, xVersion, dataSyncApiJobV1DeactivateJobRequest);
        }

        /// <summary>
        /// Test DeleteTenantDataSyncJob
        /// </summary>
        [Fact]
        public void DeleteTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1DeleteJobRequest? dataSyncApiJobV1DeleteJobRequest = null;
            //instance.DeleteTenantDataSyncJob(tenantId, jobId, apiVersion, xVersion, dataSyncApiJobV1DeleteJobRequest);
        }

        /// <summary>
        /// Test ExecuteTenantDataSyncJob
        /// </summary>
        [Fact]
        public void ExecuteTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1ExecuteJobRequest? dataSyncApiJobV1ExecuteJobRequest = null;
            //instance.ExecuteTenantDataSyncJob(tenantId, jobId, apiVersion, xVersion, dataSyncApiJobV1ExecuteJobRequest);
        }

        /// <summary>
        /// Test GetAllTenantDataSyncJobs
        /// </summary>
        [Fact]
        public void GetAllTenantDataSyncJobsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //int? pageSize = null;
            //int? pageIndex = null;
            //string? orderBy = null;
            //string? filter = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetAllTenantDataSyncJobs(tenantId, pageSize, pageIndex, orderBy, filter, apiVersion, xVersion);
            //Assert.IsType<DataSyncApiJobV1JobListResponsePaginatedItemsViewModel>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncJobProfileById
        /// </summary>
        [Fact]
        public void GetTenantDataSyncJobProfileByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncJobProfileById(tenantId, jobId, apiVersion, xVersion);
            //Assert.IsType<DataSyncApiJobV1JobProfileResponse>(response);
        }

        /// <summary>
        /// Test UpdateTenantDataSyncJob
        /// </summary>
        [Fact]
        public void UpdateTenantDataSyncJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string jobId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //DataSyncApiJobV1UpdateJobRequest? dataSyncApiJobV1UpdateJobRequest = null;
            //instance.UpdateTenantDataSyncJob(tenantId, jobId, apiVersion, xVersion, dataSyncApiJobV1UpdateJobRequest);
        }
    }
}
