/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Api;
// uncomment below to import models
//using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Test.Api
{
    /// <summary>
    ///  Class for testing ProvidersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ProvidersApiTests : IDisposable
    {
        private ProvidersApi instance;

        public ProvidersApiTests()
        {
            instance = new ProvidersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProvidersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ProvidersApi
            //Assert.IsType<ProvidersApi>(instance);
        }

        /// <summary>
        /// Test GetAllTenantDataSyncProviders
        /// </summary>
        [Fact]
        public void GetAllTenantDataSyncProvidersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //int? pageSize = null;
            //int? pageIndex = null;
            //string? orderBy = null;
            //string? filter = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetAllTenantDataSyncProviders(tenantId, pageSize, pageIndex, orderBy, filter, apiVersion, xVersion);
            //Assert.IsType<DataSyncApiProviderV1ProviderListResponsePaginatedItemsViewModel>(response);
        }

        /// <summary>
        /// Test GetTenantDataSyncProviderProfileById
        /// </summary>
        [Fact]
        public void GetTenantDataSyncProviderProfileByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tenantId = null;
            //string providerId = null;
            //string? apiVersion = null;
            //string? xVersion = null;
            //var response = instance.GetTenantDataSyncProviderProfileById(tenantId, providerId, apiVersion, xVersion);
            //Assert.IsType<DataSyncApiProviderV1ProviderProfileResponse>(response);
        }
    }
}
