/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdGraph.Datasync.Client.Client.OpenAPIDateConverter;

namespace EdGraph.Datasync.Client.Model
{
    /// <summary>
    /// DataSyncApiJobExecutionV1JobExecutionListResponse
    /// </summary>
    [DataContract(Name = "DataSyncApi.JobExecution.V1.JobExecutionListResponse")]
    public partial class DataSyncApiJobExecutionV1JobExecutionListResponse : IEquatable<DataSyncApiJobExecutionV1JobExecutionListResponse>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets JobExecutionStatus
        /// </summary>
        [DataMember(Name = "jobExecutionStatus", EmitDefaultValue = false)]
        public DataSyncApiJobExecutionV1JobExecutionStatus? JobExecutionStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DataSyncApiJobExecutionV1JobExecutionListResponse" /> class.
        /// </summary>
        /// <param name="tenantId">tenantId.</param>
        /// <param name="jobId">jobId.</param>
        /// <param name="applicationId">applicationId.</param>
        /// <param name="jobExecutionId">jobExecutionId.</param>
        /// <param name="jobExecutionStatus">jobExecutionStatus.</param>
        /// <param name="jobExecutionStartDateTime">jobExecutionStartDateTime.</param>
        /// <param name="jobExecutionEndDateTime">jobExecutionEndDateTime.</param>
        public DataSyncApiJobExecutionV1JobExecutionListResponse(string tenantId = default(string), string jobId = default(string), string applicationId = default(string), string jobExecutionId = default(string), DataSyncApiJobExecutionV1JobExecutionStatus? jobExecutionStatus = default(DataSyncApiJobExecutionV1JobExecutionStatus?), string jobExecutionStartDateTime = default(string), string jobExecutionEndDateTime = default(string))
        {
            this.TenantId = tenantId;
            this.JobId = jobId;
            this.ApplicationId = applicationId;
            this.JobExecutionId = jobExecutionId;
            this.JobExecutionStatus = jobExecutionStatus;
            this.JobExecutionStartDateTime = jobExecutionStartDateTime;
            this.JobExecutionEndDateTime = jobExecutionEndDateTime;
        }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [DataMember(Name = "tenantId", EmitDefaultValue = true)]
        public string TenantId { get; set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [DataMember(Name = "jobId", EmitDefaultValue = true)]
        public string JobId { get; set; }

        /// <summary>
        /// Gets or Sets ApplicationId
        /// </summary>
        [DataMember(Name = "applicationId", EmitDefaultValue = true)]
        public string ApplicationId { get; set; }

        /// <summary>
        /// Gets or Sets JobExecutionId
        /// </summary>
        [DataMember(Name = "jobExecutionId", EmitDefaultValue = true)]
        public string JobExecutionId { get; set; }

        /// <summary>
        /// Gets or Sets JobExecutionStartDateTime
        /// </summary>
        [DataMember(Name = "jobExecutionStartDateTime", EmitDefaultValue = true)]
        public string JobExecutionStartDateTime { get; set; }

        /// <summary>
        /// Gets or Sets JobExecutionEndDateTime
        /// </summary>
        [DataMember(Name = "jobExecutionEndDateTime", EmitDefaultValue = true)]
        public string JobExecutionEndDateTime { get; set; }

        /// <summary>
        /// Gets or Sets ChildJobs
        /// </summary>
        [DataMember(Name = "childJobs", EmitDefaultValue = true)]
        public List<DataSyncApiJobExecutionV1ChildJob> ChildJobs { get; private set; }

        /// <summary>
        /// Returns false as ChildJobs should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeChildJobs()
        {
            return false;
        }
        /// <summary>
        /// Gets or Sets Metrics
        /// </summary>
        [DataMember(Name = "metrics", EmitDefaultValue = true)]
        public List<DataSyncApiJobExecutionV1Metric> Metrics { get; private set; }

        /// <summary>
        /// Returns false as Metrics should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMetrics()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DataSyncApiJobExecutionV1JobExecutionListResponse {\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  ApplicationId: ").Append(ApplicationId).Append("\n");
            sb.Append("  JobExecutionId: ").Append(JobExecutionId).Append("\n");
            sb.Append("  JobExecutionStatus: ").Append(JobExecutionStatus).Append("\n");
            sb.Append("  JobExecutionStartDateTime: ").Append(JobExecutionStartDateTime).Append("\n");
            sb.Append("  JobExecutionEndDateTime: ").Append(JobExecutionEndDateTime).Append("\n");
            sb.Append("  ChildJobs: ").Append(ChildJobs).Append("\n");
            sb.Append("  Metrics: ").Append(Metrics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataSyncApiJobExecutionV1JobExecutionListResponse);
        }

        /// <summary>
        /// Returns true if DataSyncApiJobExecutionV1JobExecutionListResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DataSyncApiJobExecutionV1JobExecutionListResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataSyncApiJobExecutionV1JobExecutionListResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TenantId == input.TenantId ||
                    (this.TenantId != null &&
                    this.TenantId.Equals(input.TenantId))
                ) && 
                (
                    this.JobId == input.JobId ||
                    (this.JobId != null &&
                    this.JobId.Equals(input.JobId))
                ) && 
                (
                    this.ApplicationId == input.ApplicationId ||
                    (this.ApplicationId != null &&
                    this.ApplicationId.Equals(input.ApplicationId))
                ) && 
                (
                    this.JobExecutionId == input.JobExecutionId ||
                    (this.JobExecutionId != null &&
                    this.JobExecutionId.Equals(input.JobExecutionId))
                ) && 
                (
                    this.JobExecutionStatus == input.JobExecutionStatus ||
                    this.JobExecutionStatus.Equals(input.JobExecutionStatus)
                ) && 
                (
                    this.JobExecutionStartDateTime == input.JobExecutionStartDateTime ||
                    (this.JobExecutionStartDateTime != null &&
                    this.JobExecutionStartDateTime.Equals(input.JobExecutionStartDateTime))
                ) && 
                (
                    this.JobExecutionEndDateTime == input.JobExecutionEndDateTime ||
                    (this.JobExecutionEndDateTime != null &&
                    this.JobExecutionEndDateTime.Equals(input.JobExecutionEndDateTime))
                ) && 
                (
                    this.ChildJobs == input.ChildJobs ||
                    this.ChildJobs != null &&
                    input.ChildJobs != null &&
                    this.ChildJobs.SequenceEqual(input.ChildJobs)
                ) && 
                (
                    this.Metrics == input.Metrics ||
                    this.Metrics != null &&
                    input.Metrics != null &&
                    this.Metrics.SequenceEqual(input.Metrics)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TenantId != null)
                {
                    hashCode = (hashCode * 59) + this.TenantId.GetHashCode();
                }
                if (this.JobId != null)
                {
                    hashCode = (hashCode * 59) + this.JobId.GetHashCode();
                }
                if (this.ApplicationId != null)
                {
                    hashCode = (hashCode * 59) + this.ApplicationId.GetHashCode();
                }
                if (this.JobExecutionId != null)
                {
                    hashCode = (hashCode * 59) + this.JobExecutionId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.JobExecutionStatus.GetHashCode();
                if (this.JobExecutionStartDateTime != null)
                {
                    hashCode = (hashCode * 59) + this.JobExecutionStartDateTime.GetHashCode();
                }
                if (this.JobExecutionEndDateTime != null)
                {
                    hashCode = (hashCode * 59) + this.JobExecutionEndDateTime.GetHashCode();
                }
                if (this.ChildJobs != null)
                {
                    hashCode = (hashCode * 59) + this.ChildJobs.GetHashCode();
                }
                if (this.Metrics != null)
                {
                    hashCode = (hashCode * 59) + this.Metrics.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
