/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1DeleteJobRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1DeleteJobRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1DeleteJobRequest
        //private DataSyncApiJobV1DeleteJobRequest instance;

        public DataSyncApiJobV1DeleteJobRequestTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1DeleteJobRequest
            //instance = new DataSyncApiJobV1DeleteJobRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1DeleteJobRequest
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1DeleteJobRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1DeleteJobRequest
            //Assert.IsType<DataSyncApiJobV1DeleteJobRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
