/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel
        //private DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel instance;

        public DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModelTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel
            //instance = new DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel
        /// </summary>
        [Fact]
        public void DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel
            //Assert.IsType<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
