/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1JobListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1JobListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1JobListResponse
        //private DataSyncApiJobV1JobListResponse instance;

        public DataSyncApiJobV1JobListResponseTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1JobListResponse
            //instance = new DataSyncApiJobV1JobListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1JobListResponse
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1JobListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1JobListResponse
            //Assert.IsType<DataSyncApiJobV1JobListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'JobTypeId'
        /// </summary>
        [Fact]
        public void JobTypeIdTest()
        {
            // TODO unit test for the property 'JobTypeId'
        }

        /// <summary>
        /// Test the property 'JobTypeName'
        /// </summary>
        [Fact]
        public void JobTypeNameTest()
        {
            // TODO unit test for the property 'JobTypeName'
        }

        /// <summary>
        /// Test the property 'SourceConnectionId'
        /// </summary>
        [Fact]
        public void SourceConnectionIdTest()
        {
            // TODO unit test for the property 'SourceConnectionId'
        }

        /// <summary>
        /// Test the property 'DestinationConnectionId'
        /// </summary>
        [Fact]
        public void DestinationConnectionIdTest()
        {
            // TODO unit test for the property 'DestinationConnectionId'
        }

        /// <summary>
        /// Test the property 'ProfileId'
        /// </summary>
        [Fact]
        public void ProfileIdTest()
        {
            // TODO unit test for the property 'ProfileId'
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'Schedule'
        /// </summary>
        [Fact]
        public void ScheduleTest()
        {
            // TODO unit test for the property 'Schedule'
        }

        /// <summary>
        /// Test the property 'JobStatus'
        /// </summary>
        [Fact]
        public void JobStatusTest()
        {
            // TODO unit test for the property 'JobStatus'
        }

        /// <summary>
        /// Test the property 'JobExecutionId'
        /// </summary>
        [Fact]
        public void JobExecutionIdTest()
        {
            // TODO unit test for the property 'JobExecutionId'
        }

        /// <summary>
        /// Test the property 'JobExecutionStatus'
        /// </summary>
        [Fact]
        public void JobExecutionStatusTest()
        {
            // TODO unit test for the property 'JobExecutionStatus'
        }

        /// <summary>
        /// Test the property 'JobExecutionStartDateTime'
        /// </summary>
        [Fact]
        public void JobExecutionStartDateTimeTest()
        {
            // TODO unit test for the property 'JobExecutionStartDateTime'
        }

        /// <summary>
        /// Test the property 'JobExecutionEndDateTime'
        /// </summary>
        [Fact]
        public void JobExecutionEndDateTimeTest()
        {
            // TODO unit test for the property 'JobExecutionEndDateTime'
        }

        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }

        /// <summary>
        /// Test the property 'ChildJobs'
        /// </summary>
        [Fact]
        public void ChildJobsTest()
        {
            // TODO unit test for the property 'ChildJobs'
        }

        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }

        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Fact]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }

        /// <summary>
        /// Test the property 'LastModifiedBy'
        /// </summary>
        [Fact]
        public void LastModifiedByTest()
        {
            // TODO unit test for the property 'LastModifiedBy'
        }

        /// <summary>
        /// Test the property 'LastModifiedDateTime'
        /// </summary>
        [Fact]
        public void LastModifiedDateTimeTest()
        {
            // TODO unit test for the property 'LastModifiedDateTime'
        }
    }
}
