/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1JobMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1JobMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1JobMetadata
        //private DataSyncApiJobV1JobMetadata instance;

        public DataSyncApiJobV1JobMetadataTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1JobMetadata
            //instance = new DataSyncApiJobV1JobMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1JobMetadata
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1JobMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1JobMetadata
            //Assert.IsType<DataSyncApiJobV1JobMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
    }
}
