/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1Schedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1ScheduleTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1Schedule
        //private DataSyncApiJobV1Schedule instance;

        public DataSyncApiJobV1ScheduleTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1Schedule
            //instance = new DataSyncApiJobV1Schedule();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1Schedule
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1ScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1Schedule
            //Assert.IsType<DataSyncApiJobV1Schedule>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'BeginDate'
        /// </summary>
        [Fact]
        public void BeginDateTest()
        {
            // TODO unit test for the property 'BeginDate'
        }

        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }

        /// <summary>
        /// Test the property 'Cron'
        /// </summary>
        [Fact]
        public void CronTest()
        {
            // TODO unit test for the property 'Cron'
        }

        /// <summary>
        /// Test the property 'VarTimeZone'
        /// </summary>
        [Fact]
        public void VarTimeZoneTest()
        {
            // TODO unit test for the property 'VarTimeZone'
        }
    }
}
