/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobExecutionLogV1JobExecutionLogEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobExecutionLogV1JobExecutionLogEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobExecutionLogV1JobExecutionLogEntry
        //private DataSyncApiJobExecutionLogV1JobExecutionLogEntry instance;

        public DataSyncApiJobExecutionLogV1JobExecutionLogEntryTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobExecutionLogV1JobExecutionLogEntry
            //instance = new DataSyncApiJobExecutionLogV1JobExecutionLogEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobExecutionLogV1JobExecutionLogEntry
        /// </summary>
        [Fact]
        public void DataSyncApiJobExecutionLogV1JobExecutionLogEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobExecutionLogV1JobExecutionLogEntry
            //Assert.IsType<DataSyncApiJobExecutionLogV1JobExecutionLogEntry>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'JobExecutionId'
        /// </summary>
        [Fact]
        public void JobExecutionIdTest()
        {
            // TODO unit test for the property 'JobExecutionId'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'MessageType'
        /// </summary>
        [Fact]
        public void MessageTypeTest()
        {
            // TODO unit test for the property 'MessageType'
        }

        /// <summary>
        /// Test the property 'LoggedDateTime'
        /// </summary>
        [Fact]
        public void LoggedDateTimeTest()
        {
            // TODO unit test for the property 'LoggedDateTime'
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }
    }
}
