/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1JobListResponsePaginatedItemsViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1JobListResponsePaginatedItemsViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1JobListResponsePaginatedItemsViewModel
        //private DataSyncApiJobV1JobListResponsePaginatedItemsViewModel instance;

        public DataSyncApiJobV1JobListResponsePaginatedItemsViewModelTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1JobListResponsePaginatedItemsViewModel
            //instance = new DataSyncApiJobV1JobListResponsePaginatedItemsViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1JobListResponsePaginatedItemsViewModel
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1JobListResponsePaginatedItemsViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1JobListResponsePaginatedItemsViewModel
            //Assert.IsType<DataSyncApiJobV1JobListResponsePaginatedItemsViewModel>(instance);
        }

        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Fact]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
