/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1ExecuteJobRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1ExecuteJobRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1ExecuteJobRequest
        //private DataSyncApiJobV1ExecuteJobRequest instance;

        public DataSyncApiJobV1ExecuteJobRequestTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1ExecuteJobRequest
            //instance = new DataSyncApiJobV1ExecuteJobRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1ExecuteJobRequest
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1ExecuteJobRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1ExecuteJobRequest
            //Assert.IsType<DataSyncApiJobV1ExecuteJobRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'ChildJobId'
        /// </summary>
        [Fact]
        public void ChildJobIdTest()
        {
            // TODO unit test for the property 'ChildJobId'
        }

        /// <summary>
        /// Test the property 'DataRefreshType'
        /// </summary>
        [Fact]
        public void DataRefreshTypeTest()
        {
            // TODO unit test for the property 'DataRefreshType'
        }

        /// <summary>
        /// Test the property 'DataRefreshSpecificDate'
        /// </summary>
        [Fact]
        public void DataRefreshSpecificDateTest()
        {
            // TODO unit test for the property 'DataRefreshSpecificDate'
        }
    }
}
