/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobExecutionV1JobExecutionListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobExecutionV1JobExecutionListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobExecutionV1JobExecutionListResponse
        //private DataSyncApiJobExecutionV1JobExecutionListResponse instance;

        public DataSyncApiJobExecutionV1JobExecutionListResponseTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobExecutionV1JobExecutionListResponse
            //instance = new DataSyncApiJobExecutionV1JobExecutionListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobExecutionV1JobExecutionListResponse
        /// </summary>
        [Fact]
        public void DataSyncApiJobExecutionV1JobExecutionListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobExecutionV1JobExecutionListResponse
            //Assert.IsType<DataSyncApiJobExecutionV1JobExecutionListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

        /// <summary>
        /// Test the property 'ApplicationId'
        /// </summary>
        [Fact]
        public void ApplicationIdTest()
        {
            // TODO unit test for the property 'ApplicationId'
        }

        /// <summary>
        /// Test the property 'JobExecutionId'
        /// </summary>
        [Fact]
        public void JobExecutionIdTest()
        {
            // TODO unit test for the property 'JobExecutionId'
        }

        /// <summary>
        /// Test the property 'JobExecutionStatus'
        /// </summary>
        [Fact]
        public void JobExecutionStatusTest()
        {
            // TODO unit test for the property 'JobExecutionStatus'
        }

        /// <summary>
        /// Test the property 'JobExecutionStartDateTime'
        /// </summary>
        [Fact]
        public void JobExecutionStartDateTimeTest()
        {
            // TODO unit test for the property 'JobExecutionStartDateTime'
        }

        /// <summary>
        /// Test the property 'JobExecutionEndDateTime'
        /// </summary>
        [Fact]
        public void JobExecutionEndDateTimeTest()
        {
            // TODO unit test for the property 'JobExecutionEndDateTime'
        }

        /// <summary>
        /// Test the property 'ChildJobs'
        /// </summary>
        [Fact]
        public void ChildJobsTest()
        {
            // TODO unit test for the property 'ChildJobs'
        }

        /// <summary>
        /// Test the property 'Metrics'
        /// </summary>
        [Fact]
        public void MetricsTest()
        {
            // TODO unit test for the property 'Metrics'
        }
    }
}
