/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobExecutionV1JobExecutionStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobExecutionV1JobExecutionStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobExecutionV1JobExecutionStatus
        //private DataSyncApiJobExecutionV1JobExecutionStatus instance;

        public DataSyncApiJobExecutionV1JobExecutionStatusTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobExecutionV1JobExecutionStatus
            //instance = new DataSyncApiJobExecutionV1JobExecutionStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobExecutionV1JobExecutionStatus
        /// </summary>
        [Fact]
        public void DataSyncApiJobExecutionV1JobExecutionStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobExecutionV1JobExecutionStatus
            //Assert.IsType<DataSyncApiJobExecutionV1JobExecutionStatus>(instance);
        }
    }
}
