/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiConnectionV1ConnectionMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiConnectionV1ConnectionMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiConnectionV1ConnectionMetadata
        //private DataSyncApiConnectionV1ConnectionMetadata instance;

        public DataSyncApiConnectionV1ConnectionMetadataTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiConnectionV1ConnectionMetadata
            //instance = new DataSyncApiConnectionV1ConnectionMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiConnectionV1ConnectionMetadata
        /// </summary>
        [Fact]
        public void DataSyncApiConnectionV1ConnectionMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiConnectionV1ConnectionMetadata
            //Assert.IsType<DataSyncApiConnectionV1ConnectionMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'IsSecret'
        /// </summary>
        [Fact]
        public void IsSecretTest()
        {
            // TODO unit test for the property 'IsSecret'
        }
    }
}
