/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiJobV1JobStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiJobV1JobStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiJobV1JobStatus
        //private DataSyncApiJobV1JobStatus instance;

        public DataSyncApiJobV1JobStatusTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiJobV1JobStatus
            //instance = new DataSyncApiJobV1JobStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiJobV1JobStatus
        /// </summary>
        [Fact]
        public void DataSyncApiJobV1JobStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiJobV1JobStatus
            //Assert.IsType<DataSyncApiJobV1JobStatus>(instance);
        }
    }
}
