/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EdGraph.Datasync.Client.Model;
using EdGraph.Datasync.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace EdGraph.Datasync.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataSyncApiConnectionV1UpdateConnectionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataSyncApiConnectionV1UpdateConnectionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataSyncApiConnectionV1UpdateConnectionRequest
        //private DataSyncApiConnectionV1UpdateConnectionRequest instance;

        public DataSyncApiConnectionV1UpdateConnectionRequestTests()
        {
            // TODO uncomment below to create an instance of DataSyncApiConnectionV1UpdateConnectionRequest
            //instance = new DataSyncApiConnectionV1UpdateConnectionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataSyncApiConnectionV1UpdateConnectionRequest
        /// </summary>
        [Fact]
        public void DataSyncApiConnectionV1UpdateConnectionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataSyncApiConnectionV1UpdateConnectionRequest
            //Assert.IsType<DataSyncApiConnectionV1UpdateConnectionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'ConnectionId'
        /// </summary>
        [Fact]
        public void ConnectionIdTest()
        {
            // TODO unit test for the property 'ConnectionId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'ConnectionMetadata'
        /// </summary>
        [Fact]
        public void ConnectionMetadataTest()
        {
            // TODO unit test for the property 'ConnectionMetadata'
        }

        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Fact]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }

        /// <summary>
        /// Test the property 'ConnectionTypeId'
        /// </summary>
        [Fact]
        public void ConnectionTypeIdTest()
        {
            // TODO unit test for the property 'ConnectionTypeId'
        }
    }
}
