/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Client.Auth;
using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConnectionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creates a new DataSync connection
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void CreateTenantDataSyncConnection(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0);

        /// <summary>
        /// Creates a new DataSync connection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> CreateTenantDataSyncConnectionWithHttpInfo(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0);
        /// <summary>
        /// Delete a DataSync connection matching the primary key
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void DeleteTenantDataSyncConnection(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0);

        /// <summary>
        /// Delete a DataSync connection matching the primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteTenantDataSyncConnectionWithHttpInfo(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0);
        /// <summary>
        /// Retrieves a list of DataSync Connections
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel</returns>
        DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel GetAllTenantDataSyncConnections(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);

        /// <summary>
        /// Retrieves a list of DataSync Connections
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel</returns>
        ApiResponse<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel> GetAllTenantDataSyncConnectionsWithHttpInfo(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);
        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataSyncApiConnectionV1ConnectionProfileResponse</returns>
        DataSyncApiConnectionV1ConnectionProfileResponse GetTenantDataSyncConnectionProfileById(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);

        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataSyncApiConnectionV1ConnectionProfileResponse</returns>
        ApiResponse<DataSyncApiConnectionV1ConnectionProfileResponse> GetTenantDataSyncConnectionProfileByIdWithHttpInfo(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);
        /// <summary>
        /// Updates a DataSync connection matching the primary key
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        void UpdateTenantDataSyncConnection(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0);

        /// <summary>
        /// Updates a DataSync connection matching the primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UpdateTenantDataSyncConnectionWithHttpInfo(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConnectionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Creates a new DataSync connection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task CreateTenantDataSyncConnectionAsync(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Creates a new DataSync connection
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> CreateTenantDataSyncConnectionWithHttpInfoAsync(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete a DataSync connection matching the primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteTenantDataSyncConnectionAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a DataSync connection matching the primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteTenantDataSyncConnectionWithHttpInfoAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retrieves a list of DataSync Connections
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel</returns>
        System.Threading.Tasks.Task<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel> GetAllTenantDataSyncConnectionsAsync(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieves a list of DataSync Connections
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel>> GetAllTenantDataSyncConnectionsWithHttpInfoAsync(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataSyncApiConnectionV1ConnectionProfileResponse</returns>
        System.Threading.Tasks.Task<DataSyncApiConnectionV1ConnectionProfileResponse> GetTenantDataSyncConnectionProfileByIdAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataSyncApiConnectionV1ConnectionProfileResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataSyncApiConnectionV1ConnectionProfileResponse>> GetTenantDataSyncConnectionProfileByIdWithHttpInfoAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Updates a DataSync connection matching the primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UpdateTenantDataSyncConnectionAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Updates a DataSync connection matching the primary key
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateTenantDataSyncConnectionWithHttpInfoAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IConnectionsApi : IConnectionsApiSync, IConnectionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ConnectionsApi : IConnectionsApi
    {
        private EdGraph.Datasync.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConnectionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ConnectionsApi(string basePath)
        {
            this.Configuration = EdGraph.Datasync.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Datasync.Client.Client.GlobalConfiguration.Instance,
                new EdGraph.Datasync.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = EdGraph.Datasync.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ConnectionsApi(EdGraph.Datasync.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = EdGraph.Datasync.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Datasync.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = EdGraph.Datasync.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ConnectionsApi(EdGraph.Datasync.Client.Client.ISynchronousClient client, EdGraph.Datasync.Client.Client.IAsynchronousClient asyncClient, EdGraph.Datasync.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = EdGraph.Datasync.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public EdGraph.Datasync.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public EdGraph.Datasync.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public EdGraph.Datasync.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public EdGraph.Datasync.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Creates a new DataSync connection 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void CreateTenantDataSyncConnection(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0)
        {
            CreateTenantDataSyncConnectionWithHttpInfo(tenantId, apiVersion, xVersion, dataSyncApiConnectionV1CreateConnectionRequest);
        }

        /// <summary>
        /// Creates a new DataSync connection 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public EdGraph.Datasync.Client.Client.ApiResponse<Object> CreateTenantDataSyncConnectionWithHttpInfo(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0)
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->CreateTenantDataSyncConnection");
            }

            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = dataSyncApiConnectionV1CreateConnectionRequest;

            localVarRequestOptions.Operation = "ConnectionsApi.CreateTenantDataSyncConnection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/tenants/{tenantId}/datasync/connections/create", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTenantDataSyncConnection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates a new DataSync connection 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task CreateTenantDataSyncConnectionAsync(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await CreateTenantDataSyncConnectionWithHttpInfoAsync(tenantId, apiVersion, xVersion, dataSyncApiConnectionV1CreateConnectionRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Creates a new DataSync connection 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1CreateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<EdGraph.Datasync.Client.Client.ApiResponse<Object>> CreateTenantDataSyncConnectionWithHttpInfoAsync(string tenantId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1CreateConnectionRequest? dataSyncApiConnectionV1CreateConnectionRequest = default(DataSyncApiConnectionV1CreateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->CreateTenantDataSyncConnection");
            }


            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = dataSyncApiConnectionV1CreateConnectionRequest;

            localVarRequestOptions.Operation = "ConnectionsApi.CreateTenantDataSyncConnection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/tenants/{tenantId}/datasync/connections/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTenantDataSyncConnection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void DeleteTenantDataSyncConnection(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0)
        {
            DeleteTenantDataSyncConnectionWithHttpInfo(tenantId, connectionId, apiVersion, xVersion, dataSyncApiConnectionV1DeleteConnectionRequest);
        }

        /// <summary>
        /// Delete a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public EdGraph.Datasync.Client.Client.ApiResponse<Object> DeleteTenantDataSyncConnectionWithHttpInfo(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0)
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->DeleteTenantDataSyncConnection");
            }

            // verify the required parameter 'connectionId' is set
            if (connectionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'connectionId' when calling ConnectionsApi->DeleteTenantDataSyncConnection");
            }

            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = dataSyncApiConnectionV1DeleteConnectionRequest;

            localVarRequestOptions.Operation = "ConnectionsApi.DeleteTenantDataSyncConnection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/tenants/{tenantId}/datasync/connections/{connectionId}/delete", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteTenantDataSyncConnection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteTenantDataSyncConnectionAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteTenantDataSyncConnectionWithHttpInfoAsync(tenantId, connectionId, apiVersion, xVersion, dataSyncApiConnectionV1DeleteConnectionRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1DeleteConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<EdGraph.Datasync.Client.Client.ApiResponse<Object>> DeleteTenantDataSyncConnectionWithHttpInfoAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1DeleteConnectionRequest? dataSyncApiConnectionV1DeleteConnectionRequest = default(DataSyncApiConnectionV1DeleteConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->DeleteTenantDataSyncConnection");
            }

            // verify the required parameter 'connectionId' is set
            if (connectionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'connectionId' when calling ConnectionsApi->DeleteTenantDataSyncConnection");
            }


            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = dataSyncApiConnectionV1DeleteConnectionRequest;

            localVarRequestOptions.Operation = "ConnectionsApi.DeleteTenantDataSyncConnection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/tenants/{tenantId}/datasync/connections/{connectionId}/delete", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteTenantDataSyncConnection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a list of DataSync Connections 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel</returns>
        public DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel GetAllTenantDataSyncConnections(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel> localVarResponse = GetAllTenantDataSyncConnectionsWithHttpInfo(tenantId, pageSize, pageIndex, orderBy, filter, apiVersion, xVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of DataSync Connections 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel</returns>
        public EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel> GetAllTenantDataSyncConnectionsWithHttpInfo(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->GetAllTenantDataSyncConnections");
            }

            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "ConnectionsApi.GetAllTenantDataSyncConnections";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel>("/tenants/{tenantId}/datasync/connections", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllTenantDataSyncConnections", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a list of DataSync Connections 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel</returns>
        public async System.Threading.Tasks.Task<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel> GetAllTenantDataSyncConnectionsAsync(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel> localVarResponse = await GetAllTenantDataSyncConnectionsWithHttpInfoAsync(tenantId, pageSize, pageIndex, orderBy, filter, apiVersion, xVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of DataSync Connections 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel)</returns>
        public async System.Threading.Tasks.Task<EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel>> GetAllTenantDataSyncConnectionsWithHttpInfoAsync(string tenantId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->GetAllTenantDataSyncConnections");
            }


            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "ConnectionsApi.GetAllTenantDataSyncConnections";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DataSyncApiConnectionV1ConnectionListResponsePaginatedItemsViewModel>("/tenants/{tenantId}/datasync/connections", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllTenantDataSyncConnections", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataSyncApiConnectionV1ConnectionProfileResponse</returns>
        public DataSyncApiConnectionV1ConnectionProfileResponse GetTenantDataSyncConnectionProfileById(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionProfileResponse> localVarResponse = GetTenantDataSyncConnectionProfileByIdWithHttpInfo(tenantId, connectionId, apiVersion, xVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataSyncApiConnectionV1ConnectionProfileResponse</returns>
        public EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionProfileResponse> GetTenantDataSyncConnectionProfileByIdWithHttpInfo(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->GetTenantDataSyncConnectionProfileById");
            }

            // verify the required parameter 'connectionId' is set
            if (connectionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'connectionId' when calling ConnectionsApi->GetTenantDataSyncConnectionProfileById");
            }

            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "ConnectionsApi.GetTenantDataSyncConnectionProfileById";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DataSyncApiConnectionV1ConnectionProfileResponse>("/tenants/{tenantId}/datasync/connections/{connectionId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTenantDataSyncConnectionProfileById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataSyncApiConnectionV1ConnectionProfileResponse</returns>
        public async System.Threading.Tasks.Task<DataSyncApiConnectionV1ConnectionProfileResponse> GetTenantDataSyncConnectionProfileByIdAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionProfileResponse> localVarResponse = await GetTenantDataSyncConnectionProfileByIdWithHttpInfoAsync(tenantId, connectionId, apiVersion, xVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a specific DataSync connection using its primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataSyncApiConnectionV1ConnectionProfileResponse)</returns>
        public async System.Threading.Tasks.Task<EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiConnectionV1ConnectionProfileResponse>> GetTenantDataSyncConnectionProfileByIdWithHttpInfoAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->GetTenantDataSyncConnectionProfileById");
            }

            // verify the required parameter 'connectionId' is set
            if (connectionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'connectionId' when calling ConnectionsApi->GetTenantDataSyncConnectionProfileById");
            }


            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "ConnectionsApi.GetTenantDataSyncConnectionProfileById";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DataSyncApiConnectionV1ConnectionProfileResponse>("/tenants/{tenantId}/datasync/connections/{connectionId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTenantDataSyncConnectionProfileById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns></returns>
        public void UpdateTenantDataSyncConnection(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0)
        {
            UpdateTenantDataSyncConnectionWithHttpInfo(tenantId, connectionId, apiVersion, xVersion, dataSyncApiConnectionV1UpdateConnectionRequest);
        }

        /// <summary>
        /// Updates a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public EdGraph.Datasync.Client.Client.ApiResponse<Object> UpdateTenantDataSyncConnectionWithHttpInfo(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0)
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->UpdateTenantDataSyncConnection");
            }

            // verify the required parameter 'connectionId' is set
            if (connectionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'connectionId' when calling ConnectionsApi->UpdateTenantDataSyncConnection");
            }

            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = dataSyncApiConnectionV1UpdateConnectionRequest;

            localVarRequestOptions.Operation = "ConnectionsApi.UpdateTenantDataSyncConnection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Object>("/tenants/{tenantId}/datasync/connections/{connectionId}/update", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateTenantDataSyncConnection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UpdateTenantDataSyncConnectionAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await UpdateTenantDataSyncConnectionWithHttpInfoAsync(tenantId, connectionId, apiVersion, xVersion, dataSyncApiConnectionV1UpdateConnectionRequest, operationIndex, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Updates a DataSync connection matching the primary key 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="connectionId"></param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="dataSyncApiConnectionV1UpdateConnectionRequest"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<EdGraph.Datasync.Client.Client.ApiResponse<Object>> UpdateTenantDataSyncConnectionWithHttpInfoAsync(string tenantId, string connectionId, string? apiVersion = default(string?), string? xVersion = default(string?), DataSyncApiConnectionV1UpdateConnectionRequest? dataSyncApiConnectionV1UpdateConnectionRequest = default(DataSyncApiConnectionV1UpdateConnectionRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling ConnectionsApi->UpdateTenantDataSyncConnection");
            }

            // verify the required parameter 'connectionId' is set
            if (connectionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'connectionId' when calling ConnectionsApi->UpdateTenantDataSyncConnection");
            }


            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("connectionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(connectionId)); // path parameter
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }
            localVarRequestOptions.Data = dataSyncApiConnectionV1UpdateConnectionRequest;

            localVarRequestOptions.Operation = "ConnectionsApi.UpdateTenantDataSyncConnection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Object>("/tenants/{tenantId}/datasync/connections/{connectionId}/update", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateTenantDataSyncConnection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
