/*
 * DataSync Api
 *
 * DataSync Api - v1.0
 *
 * The version of the OpenAPI document: v1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using EdGraph.Datasync.Client.Client;
using EdGraph.Datasync.Client.Client.Auth;
using EdGraph.Datasync.Client.Model;

namespace EdGraph.Datasync.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IJobExecutionLogsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel</returns>
        DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel GetAllTenantDataSyncJobExecutionLogs(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);

        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel</returns>
        ApiResponse<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel> GetAllTenantDataSyncJobExecutionLogsWithHttpInfo(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IJobExecutionLogsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel</returns>
        System.Threading.Tasks.Task<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel> GetAllTenantDataSyncJobExecutionLogsAsync(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel>> GetAllTenantDataSyncJobExecutionLogsWithHttpInfoAsync(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IJobExecutionLogsApi : IJobExecutionLogsApiSync, IJobExecutionLogsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class JobExecutionLogsApi : IJobExecutionLogsApi
    {
        private EdGraph.Datasync.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="JobExecutionLogsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public JobExecutionLogsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JobExecutionLogsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public JobExecutionLogsApi(string basePath)
        {
            this.Configuration = EdGraph.Datasync.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Datasync.Client.Client.GlobalConfiguration.Instance,
                new EdGraph.Datasync.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = EdGraph.Datasync.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JobExecutionLogsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public JobExecutionLogsApi(EdGraph.Datasync.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = EdGraph.Datasync.Client.Client.Configuration.MergeConfigurations(
                EdGraph.Datasync.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new EdGraph.Datasync.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = EdGraph.Datasync.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="JobExecutionLogsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public JobExecutionLogsApi(EdGraph.Datasync.Client.Client.ISynchronousClient client, EdGraph.Datasync.Client.Client.IAsynchronousClient asyncClient, EdGraph.Datasync.Client.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = EdGraph.Datasync.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public EdGraph.Datasync.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public EdGraph.Datasync.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public EdGraph.Datasync.Client.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public EdGraph.Datasync.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel</returns>
        public DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel GetAllTenantDataSyncJobExecutionLogs(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel> localVarResponse = GetAllTenantDataSyncJobExecutionLogsWithHttpInfo(tenantId, jobId, jobExecutionId, pageSize, pageIndex, orderBy, filter, search, apiVersion, xVersion);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel</returns>
        public EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel> GetAllTenantDataSyncJobExecutionLogsWithHttpInfo(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling JobExecutionLogsApi->GetAllTenantDataSyncJobExecutionLogs");
            }

            // verify the required parameter 'jobId' is set
            if (jobId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'jobId' when calling JobExecutionLogsApi->GetAllTenantDataSyncJobExecutionLogs");
            }

            // verify the required parameter 'jobExecutionId' is set
            if (jobExecutionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'jobExecutionId' when calling JobExecutionLogsApi->GetAllTenantDataSyncJobExecutionLogs");
            }

            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(jobId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobExecutionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(jobExecutionId)); // path parameter
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "JobExecutionLogsApi.GetAllTenantDataSyncJobExecutionLogs";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel>("/tenants/{tenantId}/datasync/jobs/{jobId}/executions/{jobExecutionId}/logs", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllTenantDataSyncJobExecutionLogs", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel</returns>
        public async System.Threading.Tasks.Task<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel> GetAllTenantDataSyncJobExecutionLogsAsync(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel> localVarResponse = await GetAllTenantDataSyncJobExecutionLogsWithHttpInfoAsync(tenantId, jobId, jobExecutionId, pageSize, pageIndex, orderBy, filter, search, apiVersion, xVersion, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieves a list of DataSync Job Execution Logs 
        /// </summary>
        /// <exception cref="EdGraph.Datasync.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tenantId"></param>
        /// <param name="jobId"></param>
        /// <param name="jobExecutionId"></param>
        /// <param name="pageSize"> (optional, default to 10)</param>
        /// <param name="pageIndex"> (optional, default to 0)</param>
        /// <param name="orderBy"> (optional, default to &quot;&quot;)</param>
        /// <param name="filter"> (optional, default to &quot;&quot;)</param>
        /// <param name="search"> (optional, default to &quot;&quot;)</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <param name="xVersion"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel)</returns>
        public async System.Threading.Tasks.Task<EdGraph.Datasync.Client.Client.ApiResponse<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel>> GetAllTenantDataSyncJobExecutionLogsWithHttpInfoAsync(string tenantId, string jobId, string jobExecutionId, int? pageSize = default(int?), int? pageIndex = default(int?), string? orderBy = default(string?), string? filter = default(string?), string? search = default(string?), string? apiVersion = default(string?), string? xVersion = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tenantId' is set
            if (tenantId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'tenantId' when calling JobExecutionLogsApi->GetAllTenantDataSyncJobExecutionLogs");
            }

            // verify the required parameter 'jobId' is set
            if (jobId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'jobId' when calling JobExecutionLogsApi->GetAllTenantDataSyncJobExecutionLogs");
            }

            // verify the required parameter 'jobExecutionId' is set
            if (jobExecutionId == null)
            {
                throw new EdGraph.Datasync.Client.Client.ApiException(400, "Missing required parameter 'jobExecutionId' when calling JobExecutionLogsApi->GetAllTenantDataSyncJobExecutionLogs");
            }


            EdGraph.Datasync.Client.Client.RequestOptions localVarRequestOptions = new EdGraph.Datasync.Client.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = EdGraph.Datasync.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tenantId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(tenantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(jobId)); // path parameter
            localVarRequestOptions.PathParameters.Add("jobExecutionId", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(jobExecutionId)); // path parameter
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageSize", pageSize));
            }
            if (pageIndex != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "pageIndex", pageIndex));
            }
            if (orderBy != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "orderBy", orderBy));
            }
            if (filter != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "filter", filter));
            }
            if (search != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "search", search));
            }
            if (apiVersion != null)
            {
                localVarRequestOptions.QueryParameters.Add(EdGraph.Datasync.Client.Client.ClientUtils.ParameterToMultiMap("", "api-version", apiVersion));
            }
            if (xVersion != null)
            {
                localVarRequestOptions.HeaderParameters.Add("X-version", EdGraph.Datasync.Client.Client.ClientUtils.ParameterToString(xVersion)); // header parameter
            }

            localVarRequestOptions.Operation = "JobExecutionLogsApi.GetAllTenantDataSyncJobExecutionLogs";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<DataSyncApiJobExecutionLogV1JobExecutionLogEntryPaginatedItemsViewModel>("/tenants/{tenantId}/datasync/jobs/{jobId}/executions/{jobExecutionId}/logs", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAllTenantDataSyncJobExecutionLogs", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
